chunk_size: 1024
local_disk: "file:///home/ubuntu/kvcache/"
max_local_disk_size: 550
local_cpu: True
max_local_cpu_size: 60 # actually 40 + 5, set to 60 to avoid bubble
alpha: 10
policy: "ours"
rate: 0.371428571
