repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.7
  hooks:
  - id: ruff
    args: [--output-format, github, --fix]
  - id: ruff-format
# - repo: https://github.com/codespell-project/codespell
#   rev: v2.4.1
#   hooks:
#   - id: codespell
#     additional_dependencies: ['tomli']
#     args: ['--toml', 'pyproject.toml']
# - repo: https://github.com/PyCQA/isort
#   rev: 6.0.1
#   hooks:
#   - id: isort
# - repo: https://github.com/pre-commit/mirrors-clang-format
#   rev: v20.1.3
#   hooks:
#   - id: clang-format
#     types_or: [c++, cuda]
#     args: [--style=file, --verbose]
# - repo: local
#   hooks:
#   - id: mypy-local
#     name: Run mypy for local Python installation
#     entry: tools/mypy.sh 0 "local"
#     language: python
#     types: [python]
#     additional_dependencies: &mypy_deps [mypy==1.11.1, types-cachetools, types-setuptools, types-PyYAML, types-requests]
#     stages: [pre-commit] # Don't run in CI
#   - id: mypy-3.10 # TODO: Use https://github.com/pre-commit/mirrors-mypy when mypy setup is less awkward
#     name: Run mypy for Python 3.10
#     entry: tools/mypy.sh 1 "3.10"
#     language: python
#     types: [python]
#     additional_dependencies: *mypy_deps
#     stages: [manual] # Only run in CI
#   - id: mypy-3.11 # TODO: Use https://github.com/pre-commit/mirrors-mypy when mypy setup is less awkward
#     name: Run mypy for Python 3.11
#     entry: tools/mypy.sh 1 "3.11"
#     language: python
#     types: [python]
#     additional_dependencies: *mypy_deps
#     stages: [manual] # Only run in CI
#   - id: mypy-3.12 # TODO: Use https://github.com/pre-commit/mirrors-mypy when mypy setup is less awkward
#     name: Run mypy for Python 3.12
#     entry: tools/mypy.sh 1 "3.12"
#     language: python
#     types: [python]
#     additional_dependencies: *mypy_deps
#     stages: [manual] # Only run in CI
