local_cpu: False
max_local_cpu_size: 0
max_local_disk_size: 0

enable_nixl: True
enable_xpyd: True
nixl_role: "sender"
nixl_proxy_host: "localhost" #replace with your Proxy node IP
nixl_proxy_port: 7500
nixl_buffer_size: 1610612736 # 1.5GB
nixl_buffer_device: "cuda"
