#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../../../" && pwd)"

default_out_file() {
    echo "${OUT_FILE:-${SCRIPT_DIR}/../compat_matrix.rst}"
}

default_installation_file() {
    echo "${INSTALLATION_FILE:-${SCRIPT_DIR}/../../../../docs/source/getting_started/installation.rst}"
}

cleanup_generated_matrix() {
    local out_file
    out_file="$(default_out_file)"
    if [[ -f "${out_file}" ]]; then
        rm -f "${out_file}"
        echo "[INFO] Removed generated matrix file: ${out_file}"
    fi
}

repo_slug_from_origin_url() {
    local url="${1%.git}"

    if [[ "$url" == git@github.com:* ]]; then
        url="${url#git@github.com:}"
    elif [[ "$url" == https://github.com/* ]]; then
        url="${url#https://github.com/}"
    elif [[ "$url" == http://github.com/* ]]; then
        url="${url#http://github.com/}"
    elif [[ "$url" == ssh://git@github.com/* ]]; then
        url="${url#ssh://git@github.com/}"
    fi

    echo "$url"
}

maybe_auto_submit_pr() {
    # Only runs in CI when explicitly enabled.
    if [[ "${AUTO_SUBMIT_PR:-false}" != "true" ]]; then
        return 0
    fi

    # Avoid creating PRs from PR builds.
    if [[ "${BUILDKITE_PULL_REQUEST:-false}" != "false" ]]; then
        echo "[INFO] BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}; skipping auto PR submission."
        return 0
    fi

    local token="${GITHUB_TOKEN:-${GH_TOKEN:-}}"
    if [[ -z "$token" ]]; then
        echo "[WARN] GITHUB_TOKEN/ GH_TOKEN not set; skipping auto PR submission."
        return 0
    fi

    command -v curl >/dev/null 2>&1 || {
        echo "[WARN] curl not found; skipping auto PR submission."
        return 0
    }

    # Preserve generated matrix output across branch checkouts.
    local out_file installation_file
    out_file="$(default_out_file)"
    installation_file="$(default_installation_file)"

    [[ -f "${out_file}" ]] || {
        echo "[ERROR] Compatibility matrix file not found: ${out_file}" >&2
        exit 1
    }
    [[ -f "${installation_file}" ]] || {
        echo "[ERROR] Installation doc not found: ${installation_file}" >&2
        exit 1
    }

    local tmp_out
    tmp_out="$(mktemp)"
    cp "${out_file}" "${tmp_out}"

    cd "${REPO_ROOT}"

    local base_branch="${PR_BASE_BRANCH:-dev}"
    local build_id="${BUILDKITE_BUILD_ID:-${BUILDKITE_JOB_ID:-$(date +%s)}}"
    local branch="${PR_BRANCH_PREFIX:-ci-compat-matrix-update}-${build_id}"

    # Restore a known good base ref to keep the PR diff focused.
    git fetch origin "${base_branch}" >/dev/null 2>&1 || true
    if git rev-parse --verify "origin/${base_branch}" >/dev/null 2>&1; then
        git checkout -B "${branch}" "origin/${base_branch}"
    else
        git checkout -B "${branch}"
    fi

    cp "${tmp_out}" "${out_file}"
    rm -f "${tmp_out}"

    # Generate docs changes on the new branch.
    update_matrix

    local installation_file_rel="${installation_file#${REPO_ROOT}/}"
    if git diff --quiet -- "${installation_file_rel}"; then
        echo "[INFO] installation.rst unchanged after update_matrix; no PR created."
        return 0
    fi

    local commit_msg="${PR_COMMIT_MESSAGE:-chore: update compatibility matrix}"
    local pr_title="${PR_TITLE:-[CI] Update vLLM/LMCache compatibility matrix}"
    local pr_body="${PR_BODY:-Automatically generated by .buildkite/k3_tests/compatible tests.}"

    git config user.name "${PR_BOT_NAME:-lmcache-ci-bot}"
    git config user.email "${PR_BOT_EMAIL:-lmcache-ci@example.com}"

    git add "${installation_file_rel}"
    git commit -m "${commit_msg}"

    local origin_url repo_slug owner encoded_token push_url
    origin_url="$(git remote get-url origin 2>/dev/null || true)"
    repo_slug="$(repo_slug_from_origin_url "${origin_url}")"

    if [[ -z "${repo_slug}" ]]; then
        echo "[ERROR] Could not infer GitHub repo slug from origin URL: ${origin_url}" >&2
        exit 1
    fi

    owner="${repo_slug%/*}"
    encoded_token="$(python3 -c 'import urllib.parse,sys; print(urllib.parse.quote(sys.argv[1], safe=""))' "${token}")"
    push_url="https://x-access-token:${encoded_token}@github.com/${repo_slug}.git"

    # Push using token-authenticated URL (restore origin afterwards).
    git remote set-url origin "${push_url}"
    git push -u origin "${branch}"
    [[ -n "${origin_url}" ]] && git remote set-url origin "${origin_url}" || true

    local github_api="${GITHUB_API_URL:-https://api.github.com}"

    # If a PR already exists for this branch, don't create duplicates.
    local existing_pr_url
    existing_pr_url="$(
        curl -fsSL \
            -H "Authorization: Bearer ${token}" \
            -H "Accept: application/vnd.github+json" \
            "${github_api}/repos/${repo_slug}/pulls?head=${owner}:${branch}&state=open&per_page=1" \
        | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d[0].get("html_url","") if d else "")'
    )"
    if [[ -n "${existing_pr_url}" ]]; then
        echo "[INFO] PR already exists: ${existing_pr_url}"
        return 0
    fi

    local pr_payload pr_url
    pr_payload="$(
        GITHUB_OWNER="${owner}" PR_HEAD_BRANCH="${branch}" PR_BASE_BRANCH="${base_branch}" PR_TITLE="${pr_title}" PR_BODY="${pr_body}" python3 - <<'PY'
import json
import os

title = os.environ["PR_TITLE"]
owner = os.environ["GITHUB_OWNER"]
head_branch = os.environ["PR_HEAD_BRANCH"]
base = os.environ["PR_BASE_BRANCH"]
body = os.environ.get("PR_BODY", "")

print(
    json.dumps(
        {
            "title": title,
            "head": f"{owner}:{head_branch}",
            "base": base,
            "body": body,
            "draft": False,
        }
    )
)
PY
    )"

    pr_url="$(
        curl -fsSL \
            -H "Authorization: Bearer ${token}" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -X POST \
            -d "${pr_payload}" \
            "${github_api}/repos/${repo_slug}/pulls" \
        | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get("html_url",""))'
    )"

    [[ -n "${pr_url}" ]] || {
        echo "[ERROR] PR creation did not return a URL." >&2
        exit 1
    }

    echo "[INFO] Opened PR: ${pr_url}"
}

compute_version_sets() {
    local installation_file
    installation_file="$(default_installation_file)"

    [[ -f "${installation_file}" ]] || {
        echo "[ERROR] Installation doc not found: ${installation_file}" >&2
        exit 1
    }

    local parsed_output line key value
    parsed_output="$(python3 - "${installation_file}" <<'PY'
from __future__ import annotations

from pathlib import Path
import json
import re
import sys
import urllib.request


def _version_key(version: str) -> tuple[int, int, int]:
    return tuple(int(part) for part in version.split("."))


def _released_versions(package: str) -> list[str]:
    url = f"https://pypi.org/pypi/{package}/json"
    with urllib.request.urlopen(url, timeout=30) as response:
        payload = json.load(response)

    versions = {
        version
        for version in payload.get("releases", {})
        if re.fullmatch(r"\d+\.\d+\.\d+", version)
    }
    return sorted(versions, key=_version_key)


def _is_later_than_0_11_x(version: str) -> bool:
    major, minor, _ = _version_key(version)
    return (major, minor) > (0, 11)


def _is_later_than_0_3_9(version: str) -> bool:
    return _version_key(version) > (0, 3, 9)


installation_file = Path(sys.argv[1])
installation_text = installation_file.read_text(encoding="utf-8")

existing_vllm = {
    (match.group(1) + ".0" if len(match.group(1).split(".")) == 2 else match.group(1))
    for match in re.finditer(r"vLLM\s+(\d+\.\d+(?:\.\d+)?)(?:\.x)?", installation_text)
    if _is_later_than_0_11_x(
        match.group(1) + ".0" if len(match.group(1).split(".")) == 2 else match.group(1)
    )
}
existing_lmcache = {
    match.group(1)
    for match in re.finditer(r"LMCache\s+(\d+\.\d+\.\d+)", installation_text)
    if _is_later_than_0_3_9(match.group(1))
}

released_vllm = _released_versions("vllm")
released_lmcache = _released_versions("lmcache")

missing_vllm_bases = [
    version
    for version in released_vllm
    if _is_later_than_0_11_x(version) and version not in existing_vllm
]
missing_lmcache = [
    version
    for version in released_lmcache
    if _is_later_than_0_3_9(version) and version not in existing_lmcache
]

vllm_bases_to_test = (
    sorted(missing_vllm_bases, key=_version_key)
    if len(missing_lmcache) == 0
    else sorted(existing_vllm.union(missing_vllm_bases), key=_version_key)
)
vllm_versions_to_test = [f"{v}.x" for v in vllm_bases_to_test]

lmcache_versions_to_test = (
    sorted(missing_lmcache, key=_version_key)
    if len(missing_vllm_bases) == 0
    else sorted(existing_lmcache.union(missing_lmcache), key=_version_key)
)
missing_vllm_versions = [f"{v}.x" for v in missing_vllm_bases]

print("VLLM_MISSING=" + ",".join(missing_vllm_versions))
print("LMCACHE_MISSING=" + ",".join(missing_lmcache))
print("VLLM_TO_TEST=" + ",".join(vllm_versions_to_test))
print("LMCACHE_TO_TEST=" + ",".join(lmcache_versions_to_test))
PY
)"

    VLLM_MISSING_CSV=""
    LMCACHE_MISSING_CSV=""
    VLLM_TO_TEST_CSV=""
    LMCACHE_TO_TEST_CSV=""

    while IFS= read -r line; do
        [[ -z "$line" ]] && continue
        key="${line%%=*}"
        value="${line#*=}"
        case "$key" in
        VLLM_MISSING) VLLM_MISSING_CSV="$value" ;;
        LMCACHE_MISSING) LMCACHE_MISSING_CSV="$value" ;;
        VLLM_TO_TEST) VLLM_TO_TEST_CSV="$value" ;;
        LMCACHE_TO_TEST) LMCACHE_TO_TEST_CSV="$value" ;;
        esac
    done <<< "${parsed_output}"

    # Basic sanity checks to avoid generating an empty matrix.
    if [[ -z "${VLLM_TO_TEST_CSV}" || -z "${LMCACHE_TO_TEST_CSV}" ]]; then
        echo "[ERROR] Computed empty version sets (VLLM_TO_TEST/ LMCACHE_TO_TEST)." >&2
        exit 1
    fi
}

check_and_update_and_submit() {
    compute_version_sets

    if [[ -z "${VLLM_MISSING_CSV}" && -z "${LMCACHE_MISSING_CSV}" ]]; then
        echo "[INFO] Compatibility matrix is up-to-date; no missing versions to test."
        cleanup_generated_matrix
        return 0
    fi

    echo "[INFO] Missing vLLM versions (PyPI releases): ${VLLM_MISSING_CSV:-<none>}"
    echo "[INFO] Missing LMCache versions (PyPI releases): ${LMCACHE_MISSING_CSV:-<none>}"

    # We only run tests for versions that are missing, but `update_matrix`
    # merges the results back into the full table in `installation.rst`.
    local installation_file
    installation_file="$(default_installation_file)"
    env VLLM_VERSIONS="${VLLM_TO_TEST_CSV}" \
        LMCACHE_VERSIONS="${LMCACHE_TO_TEST_CSV}" \
        bash "${SCRIPT_DIR}/run-compatible-test.sh"

    update_matrix
    maybe_auto_submit_pr
    cleanup_generated_matrix
}

update_matrix() {
    local script_dir out_file installation_file
    script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    out_file="${OUT_FILE:-${script_dir}/../compat_matrix.rst}"
    installation_file="${INSTALLATION_FILE:-${script_dir}/../../../../docs/source/getting_started/installation.rst}"

    [[ -f "${out_file}" ]] || {
        echo "[ERROR] Compatibility matrix file not found: ${out_file}" >&2
        echo "Run run-compatible-test.sh first, or set OUT_FILE to its output path." >&2
        exit 1
    }

    [[ -f "${installation_file}" ]] || {
        echo "[ERROR] Installation doc not found: ${installation_file}" >&2
        exit 1
    }

    python3 - "${out_file}" "${installation_file}" <<'PY'
from __future__ import annotations

from pathlib import Path
import csv
import io
import re
import sys
from typing import Any


out_file = Path(sys.argv[1])
installation_file = Path(sys.argv[2])


def norm_vllm_base(base: str) -> str:
    parts = base.split(".")
    return f"{base}.0" if len(parts) == 2 else base


def parse_csv_table(lines: list[str]) -> dict[str, Any]:
    # Locate header
    header_line = next((l for l in lines if l.strip().startswith(":header:")), None)
    if not header_line:
        raise SystemExit("[ERROR] Could not locate :header: in csv-table.")

    widths_line = next((l for l in lines if l.strip().startswith(":widths:")), "")
    widths = [int(x) for x in re.findall(r"\d+", widths_line)] if widths_line else []

    # Header tokens include: first empty header (""), then LMCache column labels.
    quoted = re.findall(r'"([^"]*)"', header_line)
    lm_labels_in_order: list[str] = []
    lm_keys_in_order: list[str] = []
    lm_label_by_key: dict[str, str] = {}
    for tok in quoted[1:]:
        m = re.search(r"LMCache\s+(\d+\.\d+(?:\.\d+)?)", tok)
        if not m:
            continue
        lm_key = m.group(1)
        lm_labels_in_order.append(tok)
        lm_keys_in_order.append(lm_key)
        lm_label_by_key[lm_key] = tok

    lm_count = len(lm_keys_in_order)
    if lm_count == 0:
        raise SystemExit("[ERROR] Could not parse LMCache columns from :header:.")

    v_label_by_key: dict[str, str] = {}
    icons_by_pair: dict[tuple[str, str], str] = {}
    v_keys_in_order: list[str] = []

    v_key_re = re.compile(r"vLLM\s+(\d+\.\d+(?:\.\d+)?)\.x")
    for l in lines:
        if "vLLM" not in l or '"' not in l or "," not in l:
            continue
        row = next(
            csv.reader(io.StringIO(l), delimiter=",", quotechar='"', skipinitialspace=True), None
        )
        if not row or len(row) < 1 + lm_count:
            continue

        row_label = row[0]
        vm = v_key_re.search(row_label)
        if not vm:
            continue
        v_key = norm_vllm_base(vm.group(1))

        if v_key not in v_label_by_key:
            v_label_by_key[v_key] = row_label
            v_keys_in_order.append(v_key)

        icons = row[1 : 1 + lm_count]
        for lm_key, icon in zip(lm_keys_in_order, icons):
            icons_by_pair[(v_key, lm_key)] = icon

    return {
        "v_keys_in_order": v_keys_in_order,
        "lm_keys_in_order": lm_keys_in_order,
        "v_label_by_key": v_label_by_key,
        "lm_label_by_key": lm_label_by_key,
        "icons_by_pair": icons_by_pair,
        "widths": widths,
    }


installation_lines = installation_file.read_text(encoding="utf-8").splitlines()
try:
    start_existing = next(
        i for i, line in enumerate(installation_lines) if line.strip() == ".. csv-table::"
    )
except StopIteration as exc:
    raise SystemExit("[ERROR] Could not locate csv-table block in installation.rst.") from exc

try:
    end_existing = next(
        i
        for i in range(start_existing + 1, len(installation_lines))
        if installation_lines[i].strip() == ".. raw:: html"
    )
except StopIteration as exc:
    raise SystemExit(
        "[ERROR] Could not locate end of compatibility matrix block in installation.rst."
    ) from exc

existing_block = installation_lines[start_existing:end_existing]
existing_parsed = parse_csv_table(existing_block)

gen_lines = out_file.read_text(encoding="utf-8").splitlines()
start_gen = next((i for i, l in enumerate(gen_lines) if l.strip() == ".. csv-table::"), None)
if start_gen is None:
    raise SystemExit(f"[ERROR] {out_file} does not start with '.. csv-table::' and cannot be used.")

gen_block = gen_lines[start_gen:]
gen_parsed = parse_csv_table(gen_block)

# Merge: keep existing order, append new versions discovered in generated output.
merged_v_order = existing_parsed["v_keys_in_order"] + [
    k for k in gen_parsed["v_keys_in_order"] if k not in existing_parsed["v_keys_in_order"]
]
merged_lm_order = existing_parsed["lm_keys_in_order"] + [
    k for k in gen_parsed["lm_keys_in_order"] if k not in existing_parsed["lm_keys_in_order"]
]

merged_icons = dict(existing_parsed["icons_by_pair"])
merged_icons.update(gen_parsed["icons_by_pair"])

merged_v_labels = dict(existing_parsed["v_label_by_key"])
merged_v_labels.update(gen_parsed["v_label_by_key"])

merged_lm_labels = dict(existing_parsed["lm_label_by_key"])
merged_lm_labels.update(gen_parsed["lm_label_by_key"])

# Preserve widths when possible; expand when new LMCache columns appear.
existing_widths: list[int] = existing_parsed.get("widths") or []
first_w = existing_widths[0] if len(existing_widths) >= 1 else 25
other_w = existing_widths[1] if len(existing_widths) >= 2 else 15
merged_widths = [first_w] + [other_w] * len(merged_lm_order)

merged_lines: list[str] = []
merged_lines.append(".. csv-table::")
merged_header = '   :header: ""' + "".join([f', "{merged_lm_labels[k]}"' for k in merged_lm_order])
merged_lines.append(merged_header)
merged_lines.append(
    f'   :widths: {", ".join(str(x) for x in merged_widths)}'
)
# Required by reStructuredText: separate csv-table options from body rows.
merged_lines.append("")

for v_key in merged_v_order:
    v_label = merged_v_labels.get(v_key, f"vLLM {v_key}.x")
    row_icons = [merged_icons.get((v_key, lm_key), "❌") for lm_key in merged_lm_order]
    merged_lines.append(
        '   "' + v_label + '"' + "".join([f', "{icon}"' for icon in row_icons])
    )

updated_lines = (
    installation_lines[:start_existing] + merged_lines + [""] + installation_lines[end_existing:]
)
installation_file.write_text("\n".join(updated_lines) + "\n", encoding="utf-8")

print(f"[INFO] Merged {out_file} into {installation_file}")
PY
}

check_matrix() {
    local script_dir installation_file
    script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    installation_file="${INSTALLATION_FILE:-${script_dir}/../../../../docs/source/getting_started/installation.rst}"

    [[ -f "${installation_file}" ]] || {
        echo "[ERROR] Installation doc not found: ${installation_file}" >&2
        exit 1
    }

    local parsed_output line key value
    parsed_output="$(python3 - "${installation_file}" <<'PY'
from pathlib import Path
import json
import re
import sys
import urllib.request


def _version_key(version: str) -> tuple[int, int, int]:
    return tuple(int(part) for part in version.split("."))


def _released_versions(package: str) -> list[str]:
    url = f"https://pypi.org/pypi/{package}/json"
    with urllib.request.urlopen(url, timeout=30) as response:
        payload = json.load(response)

    versions = {
        version
        for version in payload.get("releases", {})
        if re.fullmatch(r"\d+\.\d+\.\d+", version)
    }
    return sorted(versions, key=_version_key)


def _is_later_than_0_11_x(version: str) -> bool:
    major, minor, _ = _version_key(version)
    return (major, minor) > (0, 11)


def _is_later_than_0_3_9(version: str) -> bool:
    return _version_key(version) > (0, 3, 9)


installation_file = Path(sys.argv[1])
installation_text = installation_file.read_text(encoding="utf-8")

existing_vllm = {
    (match.group(1) + ".0" if len(match.group(1).split(".")) == 2 else match.group(1))
    for match in re.finditer(r"vLLM\s+(\d+\.\d+(?:\.\d+)?)(?:\.x)?", installation_text)
}
existing_lmcache = {
    match.group(1) for match in re.finditer(r"LMCache\s+(\d+\.\d+\.\d+)", installation_text)
}

missing_vllm = [
    f"{version}.x"
    for version in _released_versions("vllm")
    if _is_later_than_0_11_x(version) and version not in existing_vllm
]
missing_lmcache = [
    version
    for version in _released_versions("lmcache")
    if _is_later_than_0_3_9(version) and version not in existing_lmcache
]

print("VLLM_MISSING=" + ",".join(missing_vllm))
print("LMCACHE_MISSING=" + ",".join(missing_lmcache))
PY
)"

    local -a vllm_versions=()
    local -a lmcache_versions=()
    while IFS= read -r line; do
        key="${line%%=*}"
        value="${line#*=}"
        if [[ "${key}" == "VLLM_MISSING" ]]; then
            [[ -n "${value}" ]] && IFS=',' read -r -a vllm_versions <<< "${value}"
        elif [[ "${key}" == "LMCACHE_MISSING" ]]; then
            [[ -n "${value}" ]] && IFS=',' read -r -a lmcache_versions <<< "${value}"
        fi
    done <<< "${parsed_output}"

    echo "vllm_versions: ${vllm_versions[*]}"
    echo "lmcache_versions: ${lmcache_versions[*]}"
}

main() {
    case "${1:-update_matrix}" in
    check_and_update_and_submit|check_and_update)
        check_and_update_and_submit
        ;;
    update|update_matrix)
        update_matrix
        ;;
    check_missing_versions|check_matrix)
        check_matrix
        ;;
    *)
        echo "Usage: $0 [check_and_update_and_submit|check_and_update|update_matrix|check_matrix]" >&2
        exit 1
        ;;
    esac
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    main "$@"
fi
