env:
  PATH: "$HOME/.local/bin:$PATH"

steps:
  - label: ":pip: Prepare venv"
    key: "venv"
    plugins:
      - cache#v1.5.2:
          key: "venv-{{ BUILDKITE_BUILD_ID }}-{{ checksum \"requirements/common.txt\" }}-{{ checksum \"requirements/test.txt\" }}"
          path: ".venv"
          save: "pipeline"
    command:
      - echo "${BUILDKITE_BUILD_ID}"
      - bash .buildkite/install-env.sh

  - label: ":pytest: Run pytest"
    key: "pytest"
    depends_on:
      - "venv"
    timeout_in_minutes: 25
    plugins:
      - cache#v1.5.2:
          key: "venv-{{ BUILDKITE_BUILD_ID }}-{{ checksum \"requirements/common.txt\" }}-{{ checksum \"requirements/test.txt\" }}"
          path: ".venv"
          restore: "pipeline"
    command:
      - echo "${BUILDKITE_BUILD_ID}"
      - bash .buildkite/install-lmcache.sh
      - source .venv/bin/activate
      - |
        LMCACHE_TRACK_USAGE="false" \
        pytest --cov=lmcache \
          --cov-report term --cov-report=html:coverage-test \
          --cov-report=xml:coverage-test.xml --html=durations/test.html \
          --ignore=tests/disagg --ignore=tests/v1/test_pos_kernels.py
    artifact_paths:
      - "durations/test.html"
      - "coverage-test.xml"
