{{- if .Values.webhook.enabled }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Release.Name }}-mutating-webhook-configuration
  labels:
    {{- include "lmcache-operator.labels" . | nindent 4 }}
  {{- if .Values.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Release.Name }}-serving-cert
  {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Release.Name }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate--v1-pod
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  name: mcacheblendpod.lmcache.ai
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
  objectSelector:
    matchLabels:
      lmcache.ai/cacheblend-inject: "true"
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
      - kube-public
      - {{ .Release.Namespace }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Release.Name }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-lmcache--v1-pod
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  name: mlmcachepod.lmcache.ai
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
  objectSelector:
    matchLabels:
      lmcache.ai/lmcache-inject: "true"
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
      - kube-public
      - {{ .Release.Namespace }}
{{- end }}
