# vllm/vllm-openai:latest currently has lmcache bundled
# this is in case vllm does not have lmcache bundled in the future
# this docker file will not be able to run PD (no nixl)
FROM vllm/vllm-openai:latest

RUN uv pip install --system --no-cache lmcache


# Build: 
# docker build -f Dockerfile.light -t 'lmcache/vllm-openai:light' .

# Run: 
# export HF_TOKEN=<your_huggingface_token>
# docker run --runtime nvidia --gpus all \
#    -v ~/.cache/huggingface:/root/.cache/huggingface \
#    --env "HUGGING_FACE_HUB_TOKEN=$HF_TOKEN" \
#    -p 8000:8000 \
#    --ipc=host \
#    lmcache/vllm-openai:light \
#    --model Qwen/Qwen3-0.6B \
#    --kv-transfer-config \
#    '{"kv_connector":"LMCacheConnectorV1","kv_role":"kv_both"}'