// SPDX-License-Identifier: Apache-2.0
syntax = "proto3";

package lmcache.mp;

import "common.proto";

service EngineDrivenService {
  rpc RegisterKvCacheEngineDrivenContext(TransportPayload)
      returns (TransportPayload);
  rpc UnregisterKvCacheEngineDrivenContext(TransportPayload)
      returns (TransportPayload);
  rpc PrepareStore(TransportPayload) returns (TransportPayload);
  rpc CommitStore(TransportPayload) returns (TransportPayload);
  rpc PrepareRetrieve(TransportPayload) returns (TransportPayload);
  rpc CommitRetrieve(TransportPayload) returns (TransportPayload);
}
