// SPDX-License-Identifier: Apache-2.0
syntax = "proto3";

package lmcache.mp;

import "common.proto";

service LookupService {
  rpc Lookup(TransportPayload) returns (TransportPayload);
  rpc QueryPrefetchStatus(TransportPayload) returns (TransportPayload);
  rpc WaitPrefetchStatus(TransportPayload) returns (TransportPayload);
  rpc QueryPrefetchLookupHits(TransportPayload) returns (TransportPayload);
  rpc FreeLookupLocks(TransportPayload) returns (TransportPayload);
  rpc EndSession(TransportPayload) returns (TransportPayload);
}
