chunk_size: 1024

local_cpu: True
max_local_cpu_size: 40

local_disk: "file:///home/ubuntu/kvcache/"
max_local_disk_size: 120
remote_disk: "file:///home/ubuntu/kvcache_remote/"
max_remote_disk_size: 240

alpha: 1
policy: "baseline_KIVI"
rate: 0.371428571
compression: "kivi"
dataset_csv: "dataset/coding_processed_v2.csv"
method_output_csv: "results/dummy_mode.csv"