chunk_size: 1024
local_disk: "file:///home/ubuntu/st-prodstack-v/kvcache/engine4/"
max_local_disk_size: 550
local_cpu: True
max_local_cpu_size: 70 # actually 50 + 5, set to 70 to avoid bubble
alpha: 0.7
policy: "baseline_KIVI"
rate: 0.728571429
