---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-deployment
  namespace: multi-process
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-deployment
  template:
    metadata:
      labels:
        app: vllm-deployment
    spec:
      hostIPC: true
      containers:
        - name: vllm
          image: lmcache/vllm-openai:latest-nightly
          args:
            - Qwen/Qwen3-14B
            - --host
            - "0.0.0.0"
            - --port
            - "8000"
            - --no-enable-prefix-caching
            - --max-model-len
            - "32768"
            - --gpu-memory-utilization
            - "0.85"
            - --tensor-parallel-size
            - "4"
            - --kv-transfer-config
            - '{"kv_connector":"LMCacheMPConnector", "kv_role":"kv_both", "kv_connector_extra_config": {"lmcache.mp.port": 6555}}'
          resources:
            limits:
              nvidia.com/gpu: "4"
            requests:
              nvidia.com/gpu: "4"
          startupProbe:
            failureThreshold: 60
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: PYTHONHASHSEED
              value: "0"
            - name: PROMETHEUS_MULTIPROC_DIR
              value: "/tmp"
            - name: LMCACHE_LOG_LEVEL
              value: "DEBUG"
