steps:
  - label: ":pipeline: Upload merged correctness pipeline"
    key: "upload_correctness"
    command: |
      set -euo pipefail
      source .buildkite/k3_tests/common_scripts/helpers.sh
      merge_pr_base_branch
      buildkite-agent pipeline upload .buildkite/correctness/pipeline.correctness.steps.yml
