chunk_size: 1024
local_disk: "file:///home/ubuntu/kvcache/"
max_local_disk_size: 550
local_cpu: True
max_local_cpu_size: 20 # actually 40 + 5, set to 60 to avoid bubble
alpha: 1
policy: "disk"
rate: 1
