{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "lmcache-operator.resourceName" (dict "root" . "suffix" "controller-manager-metrics-monitor") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- mergeOverwrite (dict) .Values.metrics.serviceMonitor.labels (include "lmcache-operator.labels" . | fromYaml) | toYaml | nindent 4 }}
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        {{- toYaml .Values.metrics.serviceMonitor.tlsConfig | nindent 8 }}
  selector:
    matchLabels:
      {{- include "lmcache-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/component: metrics
{{- end }}
