env:
  DOCKER_BUILDKIT: 1

steps:
  - label: ":compression: Comprehensive Tests"
    key: "test"
    timeout_in_minutes: 60
    commands:
      - rm -rf /tmp/lmcache_vllm_*.log
      - chmod +x .buildkite/scripts/vllm-integration-tests.sh
      - .buildkite/scripts/vllm-integration-tests.sh --hf-token=$HF_TOKEN --server-wait-timeout=240 --tests=long-doc-qa --configs=.buildkite/cases/comprehensive-cases.txt
    artifact_paths:
      - "/tmp/lmcache_vllm_*.log"

  - label: ":broom: Clean up"
    depends_on: ["test"]
    allow_dependency_failure: true
    command: |
      export TARGET="$PWD"
      echo "Deleting current workspace $TARGET"
      cd /
      sudo rm -rf "$TARGET"