steps:
  - label: ":pipeline: Upload merged e2e pipeline"
    key: "upload_e2e"
    command: |
      set -euo pipefail
      source .buildkite/k3_tests/common_scripts/helpers.sh
      merge_pr_base_branch
      buildkite-agent pipeline upload .buildkite/pipelines/end-to-end-tests.steps.yml
