name: mypy

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  ruff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy==1.11.2
        pip install types-setuptools
        pip install types-PyYAML
        pip install types-requests
        pip install types-setuptools
        pip install redis
    - name: Mypy
      run: |
        mypy
        mypy tests --follow-imports skip
        mypy lmcache --follow-imports skip