name: "Operator: E2E Tests"

on:
  push:
    branches:
      - dev
      - "release-**"
    paths:
      - 'operator/**'
      - '.github/workflows/operator_test_e2e.yml'
  pull_request:
    branches:
      - dev
      - "release-**"
    paths:
      - 'operator/**'
      - '.github/workflows/operator_test_e2e.yml'

permissions:
  contents: read

defaults:
  run:
    shell: bash
    working-directory: operator

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: operator/go.mod

      - name: Install the latest version of kind
        run: |
          curl -Lo ./kind "https://kind.sigs.k8s.io/dl/latest/kind-linux-$(go env GOARCH)"
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Running Test e2e
        run: |
          go mod tidy
          make test-e2e
