# SPDX-License-Identifier: Apache-2.0
"""Regenerate gRPC Python stubs for the split mp transport protos.

The ``.proto`` sources live under ``../protos/`` (checked into git);
the emitted ``*_pb2.py`` / ``*_pb2_grpc.py`` files land next to this
module and are ignored by Git. Package builds include the generated
modules, so runtime users do not need ``grpcio-tools``.

Run as a module so relative paths resolve correctly::

    python -m lmcache.v1.multiprocess.transport.grpc_impl._proto_gen._generate

Requires the pinned ``requirements/proto.txt`` dependencies. The generated
files are patched so their internal imports use the full package path and so
mypy skips them. This script also writes compatibility aggregate modules named
``lmcache_mq_pb2`` and ``lmcache_mq_pb2_grpc`` so the runtime can consume one
descriptor surface even though the source schema is split by service.
"""

# Standard
from pathlib import Path
from typing import Sequence
import re
import subprocess
import sys

HERE = Path(__file__).resolve().parent
PROTO_DIR = HERE.parent / "protos"
AGGREGATE_PB2 = HERE / "lmcache_mq_pb2.py"
AGGREGATE_PB2_GRPC = HERE / "lmcache_mq_pb2_grpc.py"

SPDX_HEADER = "# SPDX-License-Identifier: Apache-2.0\n"
MYPY_IGNORE = "# mypy: ignore-errors\n"
FLAT_PB2_IMPORT_RE = re.compile(
    r"^import ([A-Za-z_][A-Za-z0-9_]*_pb2) as ([A-Za-z_][A-Za-z0-9_]*)$",
    re.MULTILINE,
)
PROTO_ORDER = {
    "common": 0,
    "engine_service": 1,
    "controller_service": 2,
    "observability_service": 3,
    "debug_service": 4,
    "blend_service": 5,
    "p2p_service": 6,
}


def _proto_sort_key(path: Path) -> tuple[int, str]:
    return (PROTO_ORDER.get(path.stem, len(PROTO_ORDER)), path.name)


def _proto_paths() -> tuple[Path, ...]:
    paths = tuple(sorted(PROTO_DIR.glob("*.proto"), key=_proto_sort_key))
    if not paths:
        raise RuntimeError(f"no proto sources found under {PROTO_DIR}")
    return paths


def _proto_module_name(path: Path) -> str:
    return path.stem


def _service_proto_module_names(proto_paths: Sequence[Path]) -> tuple[str, ...]:
    modules: list[str] = []
    for path in proto_paths:
        if re.search(r"^\s*service\s+\w+", path.read_text(), flags=re.MULTILINE):
            modules.append(_proto_module_name(path))
    return tuple(modules)


def _ensure_headers(path: Path) -> None:
    """Prepend SPDX + mypy markers if they are not already present."""
    text = path.read_text()
    prefix = ""
    if not text.startswith(SPDX_HEADER):
        prefix += SPDX_HEADER
    if MYPY_IGNORE not in text.splitlines()[:5]:
        prefix += MYPY_IGNORE
    if prefix:
        path.write_text(prefix + text)


def _patch_flat_pb2_imports(path: Path) -> None:
    text = path.read_text()

    def replace(match: re.Match[str]) -> str:
        module_name, alias = match.groups()
        return (
            "from lmcache.v1.multiprocess.transport.grpc_impl._proto_gen "
            f"import {module_name} as {alias}"
        )

    patched = FLAT_PB2_IMPORT_RE.sub(replace, text)
    if patched != text:
        path.write_text(patched)


def _module_imports(module_names: Sequence[str], suffix: str) -> str:
    return "\n".join(
        "from lmcache.v1.multiprocess.transport.grpc_impl._proto_gen "
        f"import {module_name}_{suffix} as _{module_name}_{suffix}"
        for module_name in module_names
    )


def _module_tuple(module_names: Sequence[str], suffix: str) -> str:
    return "".join(f"    _{module_name}_{suffix},\n" for module_name in module_names)


def _service_module_tuple(module_names: Sequence[str]) -> str:
    return "".join(
        f"    (_{module_name}_pb2, _{module_name}_pb2_grpc),\n"
        for module_name in module_names
    )


def _write_aggregate_pb2(module_names: Sequence[str]) -> None:
    imports = _module_imports(module_names, "pb2")
    module_tuple = _module_tuple(module_names, "pb2")
    AGGREGATE_PB2.write_text(
        f"""{SPDX_HEADER}{MYPY_IGNORE}\"\"\"Aggregate protobuf messages for LMCache
mp-mode gRPC.

Generated by ``_generate.py``. Do not edit by hand.
\"\"\"

# Standard
from types import SimpleNamespace
from typing import Any

# First Party
{imports}

_PROTO_MODULES = (
{module_tuple})


def _collect_message_classes() -> dict[str, Any]:
    messages: dict[str, Any] = {{}}
    for module in _PROTO_MODULES:
        for message_name in module.DESCRIPTOR.message_types_by_name:
            if message_name in messages:
                raise RuntimeError(f"Duplicate protobuf message: {{message_name}}")
            messages[message_name] = getattr(module, message_name)
    return messages


def _collect_service_descriptors() -> dict[str, Any]:
    services: dict[str, Any] = {{}}
    for module in _PROTO_MODULES:
        for service_name, service in module.DESCRIPTOR.services_by_name.items():
            if service_name in services:
                raise RuntimeError(f"Duplicate protobuf service: {{service_name}}")
            services[service_name] = service
    return services


_MESSAGES = _collect_message_classes()
globals().update(_MESSAGES)
DESCRIPTOR = SimpleNamespace(
    message_types_by_name=dict(_MESSAGES),
    services_by_name=_collect_service_descriptors(),
)

__all__ = [\"DESCRIPTOR\", *_MESSAGES]
"""
    )


def _write_aggregate_pb2_grpc(module_names: Sequence[str]) -> None:
    pb2_imports = _module_imports(module_names, "pb2")
    grpc_imports = _module_imports(module_names, "pb2_grpc")
    service_module_tuple = _service_module_tuple(module_names)
    AGGREGATE_PB2_GRPC.write_text(
        f"""{SPDX_HEADER}{MYPY_IGNORE}\"\"\"Aggregate gRPC service stubs for LMCache
mp-mode gRPC.

Generated by ``_generate.py``. Do not edit by hand.
\"\"\"

# Standard
from typing import Any

# First Party
{pb2_imports}
{grpc_imports}

_SERVICE_MODULES = (
{service_module_tuple})


def _export_service_symbols() -> list[str]:
    exports: list[str] = []
    for pb2_module, grpc_module in _SERVICE_MODULES:
        for service_name in pb2_module.DESCRIPTOR.services_by_name:
            for symbol in (
                f"{{service_name}}Stub",
                f"{{service_name}}Servicer",
                f"add_{{service_name}}Servicer_to_server",
            ):
                globals()[symbol] = getattr(grpc_module, symbol)
                exports.append(symbol)
    return exports


__all__ = _export_service_symbols()
"""
    )


def _cleanup_generated_files() -> None:
    for path in tuple(HERE.glob("*_pb2.py")) + tuple(HERE.glob("*_pb2_grpc.py")):
        path.unlink(missing_ok=True)


def main() -> int:
    try:
        # Third Party
        import grpc_tools.protoc  # noqa: F401
    except ImportError:
        print(
            "grpcio-tools is not installed; cannot generate gRPC stubs "
            "for the mp transport. Install it with "
            "'pip install -r requirements/proto.txt'.",
            file=sys.stderr,
        )
        return 1

    proto_paths = _proto_paths()
    proto_modules = tuple(_proto_module_name(path) for path in proto_paths)
    service_modules = _service_proto_module_names(proto_paths)

    # Never let stale output hide an invalid schema or failed generation.
    _cleanup_generated_files()

    cmd = [
        sys.executable,
        "-m",
        "grpc_tools.protoc",
        "-I",
        str(PROTO_DIR),
        "--python_out",
        str(HERE),
        "--grpc_python_out",
        str(HERE),
        *(str(path) for path in proto_paths),
    ]
    rc = subprocess.call(cmd)
    if rc != 0:
        return rc

    for path in tuple(HERE.glob("*_pb2.py")) + tuple(HERE.glob("*_pb2_grpc.py")):
        _patch_flat_pb2_imports(path)
        _ensure_headers(path)

    _write_aggregate_pb2(proto_modules)
    _write_aggregate_pb2_grpc(service_modules)

    # Health-check the freshly generated stubs in a subprocess so we do not
    # pollute the caller's sys.modules and can detect protobuf version issues.
    rc = subprocess.call(
        [
            sys.executable,
            "-c",
            (
                "from lmcache.v1.multiprocess.transport.grpc_impl._proto_gen "
                "import lmcache_mq_pb2, lmcache_mq_pb2_grpc; "
                "assert lmcache_mq_pb2.DESCRIPTOR.services_by_name; "
                "assert hasattr(lmcache_mq_pb2_grpc, 'EngineServiceStub')"
            ),
        ],
    )
    if rc != 0:
        _cleanup_generated_files()
        print(
            "generated stubs failed their import health check; install the "
            "pinned requirements/proto.txt dependencies and regenerate.",
            file=sys.stderr,
        )
        return rc

    generated = sorted(path.name for path in HERE.glob("*_pb2*.py"))
    print("generated:", ", ".join(generated))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
